/**
 * @file HeartbeatSubsystem.h
 * @brief Publishes a heartbeat message at 200 ms intervals.
 * @author Generated by Copilot
 * @date 12/16/2025
 */
#pragma once

#include <BaseSubsystem.h>
#include <micro_ros_utilities/string_utilities.h>
#include <microros_manager_robot.h>
#include <rcl/rcl.h>
#include <rclc/rclc.h>
#include <std_msgs/msg/string.h>
#include <uxr/client/util/time.h>

#include "TimedSubsystem.h"

namespace Subsystem {

class HeartbeatSubsystemSetup : public Classes::BaseSetup {
 public:
  HeartbeatSubsystemSetup(const char* _id) : Classes::BaseSetup(_id) {}
};

class HeartbeatSubsystem : public IMicroRosParticipant,
                           public Subsystem::TimedSubsystem {
 public:
  explicit HeartbeatSubsystem(const HeartbeatSubsystemSetup& setup)
      : Subsystem::TimedSubsystem(setup), setup_(setup) {}

  bool init() override { return true; }
  void begin() override {}
  void update() override {
    if (!pub_.impl) return;
    if (everyMs(200)) {
      publishHeartbeat();
    }
  }
  void pause() override {}
  void reset() override { pause(); }
  const char* getInfo() override {
    static const char info[] = "HeartbeatSubsystem";
    return info;
  }

  bool onCreate(rcl_node_t* node, rclc_executor_t* executor) override {
    (void)executor;
    node_ = node;
    if (rclc_publisher_init_best_effort(
            &pub_, node, ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, String),
            "/mcu_robot/heartbeat") != RCL_RET_OK) {
      return false;
    }
    msg_.data = micro_ros_string_utilities_set(msg_.data, "HEARTBEAT");
    return true;
  }

  void onDestroy() override {
    if (pub_.impl) {
      (void)rcl_publisher_fini(&pub_, node_);
    }
    if (msg_.data.data) {
      micro_ros_string_utilities_destroy(&msg_.data);
    }
    node_ = nullptr;
  }

 private:
  void publishHeartbeat() {
    if (!pub_.impl) return;
    msg_.data = micro_ros_string_utilities_set(msg_.data, "HEARTBEAT");
    (void)rcl_publish(&pub_, &msg_, NULL);
  }

  const HeartbeatSubsystemSetup setup_;
  rcl_publisher_t pub_{};
  std_msgs__msg__String msg_{};
  rcl_node_t* node_ = nullptr;
};

}  // namespace Subsystem
