/**
 * @file HeartbeatSubsystem.h
 * @brief Publishes a heartbeat message at regular intervals.
 * @author Generated by Copilot
 * @date 12/16/2025
 */
#pragma once

#include <BaseSubsystem.h>
#include <micro_ros_utilities/string_utilities.h>
#include "DebugLog.h"
#include <microros_manager_robot.h>
#include <rcl/rcl.h>
#include <rclc/rclc.h>
#include <std_msgs/msg/string.h>
#include <uxr/client/util/time.h>

#ifdef USE_TEENSYTHREADS
#include <TeensyThreads.h>
#endif

namespace Subsystem {

class HeartbeatSubsystemSetup : public Classes::BaseSetup {
 public:
  HeartbeatSubsystemSetup(const char* _id) : Classes::BaseSetup(_id) {}
};

class HeartbeatSubsystem : public IMicroRosParticipant,
                           public Classes::BaseSubsystem {
 public:
  explicit HeartbeatSubsystem(const HeartbeatSubsystemSetup& setup)
      : Classes::BaseSubsystem(setup), setup_(setup) {}

  bool init() override { return true; }
  void begin() override {}
  void update() override {
    if (!pub_.impl) return;
#ifdef USE_TEENSYTHREADS
    Threads::Scope lock(data_mutex_);
#endif
    data_ready_ = true;
  }
  void pause() override {}
  void reset() override { pause(); }
  const char* getInfo() override {
    static const char info[] = "HeartbeatSubsystem";
    return info;
  }

  bool onCreate(rcl_node_t* node, rclc_executor_t* executor) override {
    (void)executor;
    node_ = node;
    if (rclc_publisher_init_best_effort(
            &pub_, node, ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, String),
            "/mcu_robot/heartbeat") != RCL_RET_OK) {
      DEBUG_PRINTLN("[HB] onCreate FAIL: publisher init");
      return false;
    }
    msg_.data = micro_ros_string_utilities_set(msg_.data, "HEARTBEAT");
    DEBUG_PRINTLN("[HB] onCreate OK");
    return true;
  }

  void onDestroy() override {
    // destroy_entities() finalises the rcl_node before calling onDestroy, so
    // rcl_publisher_fini would see a dead node and fail while leaving pub_.impl
    // non-NULL — causing the update thread to publish on a stale handle.
    // The DDS resources are freed by rclc_support_fini; just reset local state.
    pub_ = rcl_get_zero_initialized_publisher();
    node_ = nullptr;
  }

#ifdef USE_TEENSYTHREADS
  void beginThreaded(uint32_t stackSize, int priority = 1,
                     uint32_t updateRateMs = 200) {
    task_delay_ms_ = updateRateMs;
    int id = threads.addThread(taskFunction, this, stackSize);
    threads.setTimeSlice(id, priority);
  }

 private:
  static void taskFunction(void* pvParams) {
    auto* self = static_cast<HeartbeatSubsystem*>(pvParams);
    self->begin();
    while (true) {
      self->update();
      threads.delay(self->task_delay_ms_);
    }
  }
  uint32_t task_delay_ms_ = 200;
#endif

 public:
  void publishAll() override {
#ifdef USE_TEENSYTHREADS
    Threads::Scope lock(data_mutex_);
    if (!data_ready_ || !pub_.impl) return;
    (void)rcl_publish(&pub_, &msg_, NULL);
    data_ready_ = false;
#endif
  }

 private:
  const HeartbeatSubsystemSetup setup_;
  rcl_publisher_t pub_{};
  std_msgs__msg__String msg_{};
  rcl_node_t* node_ = nullptr;
  bool data_ready_ = false;
#ifdef USE_TEENSYTHREADS
  Threads::Mutex data_mutex_;
#endif
};

}  // namespace Subsystem
