name: Deploy to Raspberry Pi
run-name: ${{ gitea.actor }} is deploying to /home/ieee/SEC26 🤖

on:
  push:
    branches:
      - prod
      - CD-testing
  workflow_dispatch:

jobs:
  # 0. Build MCU artifacts on amd64 to avoid ARM64 compile issues
  build-mcu-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Prepare MCU extra packages (mcu_msgs)
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p mcu_ws/extra_packages
          if [ -d ros2_ws/src/mcu_msgs ]; then
            rm -rf mcu_ws/extra_packages/mcu_msgs
            cp -a ros2_ws/src/mcu_msgs mcu_ws/extra_packages/mcu_msgs
          else
            echo "mcu_msgs not found at ros2_ws/src/mcu_msgs" >&2
            exit 1
          fi

      - name: Cache PlatformIO packages and build artifacts
        id: pio-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            mcu_ws/.pio
            mcu_ws/.pioenvs
            mcu_ws/libs_external/esp32/micro_ros_platformio/build
            mcu_ws/libs_external/esp32/micro_ros_platformio/libmicroros
            mcu_ws/libs_external/teensy/micro_ros_platformio/build
            mcu_ws/libs_external/teensy/micro_ros_platformio/libmicroros
            ~/.cache/pip
          key: platformio-lite-${{ runner.os }}-${{ hashFiles('mcu_ws/extra_packages/**','mcu_ws/libs_external/**','mcu_ws/platformio.ini') }}
          restore-keys: |
            platformio-lite-${{ runner.os }}-

      - name: Show PlatformIO cache status
        run: |
          if [ "${{ steps.pio-cache.outputs.cache-hit }}" = 'true' ]; then
            echo "::notice::PlatformIO cache hit"
          else
            echo "::notice::PlatformIO cache miss"
          fi

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build robot and robotcomms PlatformIO environments
        working-directory: mcu_ws/
        shell: bash
        run: |
          pio pkg install || true
          # Build only the required environments to speed up CI
          pio run -e robot -e robotcomms

      - name: Preview MCU artifacts (count + list)
        shell: bash
        run: |
          set -euxo pipefail
          shopt -s globstar nullglob
          files=(
            mcu_ws/.pio/build/robot/firmware.*
            mcu_ws/.pio/build/robot/**/*.hex
            mcu_ws/.pio/build/robot/**/*.elf
            mcu_ws/.pio/build/robotcomms/firmware.*
            mcu_ws/.pio/build/robotcomms/**/*.bin
            mcu_ws/.pio/build/robotcomms/**/*.elf
          )
          echo "Found ${#files[@]} files to upload:";
          for f in "${files[@]}"; do echo " - $f"; done

      - name: Upload MCU build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mcu-build-artifacts
          path: |
            mcu_ws/.pio/build/robot/firmware.*
            mcu_ws/.pio/build/robot/**/*.hex
            mcu_ws/.pio/build/robot/**/*.elf
            mcu_ws/.pio/build/robotcomms/firmware.*
            mcu_ws/.pio/build/robotcomms/**/*.bin
            mcu_ws/.pio/build/robotcomms/**/*.elf
          if-no-files-found: ignore
          retention-days: 7
  # 1. Robot Job - Always Runs
  deploy-robot:
    needs: build-mcu-artifacts
    runs-on: rpi-ros2
    
    # Force all steps to run inside your specific directory
    defaults:
      run:
        working-directory: /home/ieee/SEC26

    steps:
      - name: 📦 Download MCU build artifacts
        uses: actions/download-artifact@v3
        with:
          name: mcu-build-artifacts
          path: /home/ieee/SEC26/mcu_ws/prebuilt
        continue-on-error: true

      - name: 📄 List downloaded artifacts
        run: |
          echo "Listing prebuilt artifacts (if any):"
          ls -R mcu_ws/prebuilt || echo "No prebuilt artifacts found"
      - name: LEDs On
        run: |
          echo "⚡ LED Flashing (daemonized) during deployment"
          # Kill any lingering daemonized gpioset processes
          pkill -f "gpioset.*BOOTLED" || true
          gpioset -z -C BOOTLED -c gpiochip0 -t 200 17=1
      - name: 📂 Pull Latest Code (Robot)
        run: |
          echo "📂 Navigating to /home/ieee/SEC26..."
          git config --global --add safe.directory /home/ieee/SEC26
          git fetch --all
          echo "🔀 Switching to branch: ${{ gitea.ref_name }}"
          git reset --hard origin/${{ gitea.ref_name }}
          echo "📂 Updating submodules..."
          git submodule update --init --recursive
          echo "🔧 Fixing permissions..."
          chmod +x scripts/start_robot.sh

      - name: 🧪 Run Verification Script
        run: |
          echo "🧪 Running test script on the Pi..."
          # The verification script runs from the working-directory/scripts
          python3 scripts/test_deploy.py

      - name: 🚀 Build and Deploy (Docker)
        run: |
          echo "🚀 Rebuilding from: /home/ieee/SEC26/docker-compose.yml"
          COMPOSE_FILE="docker-compose.yml"
          
          # Check if Dockerfile has changed
          if git diff HEAD~1 HEAD --name-only 2>/dev/null | grep -q "Dockerfile\|docker-compose"; then
            echo "📝 Dockerfile or docker-compose changed; full down/rebuild/up cycle"
            docker compose -f $COMPOSE_FILE --project-directory . down || true
          else
            echo "📝 No Dockerfile/docker-compose changes; only stopping and restarting"
            docker compose -f $COMPOSE_FILE --project-directory . stop || true
          fi
          
          # Rebuild the image
          docker compose -f $COMPOSE_FILE --project-directory . build
          
          # Start the container
          docker compose -f $COMPOSE_FILE --project-directory . up -d

      - name: ▶️ Run and activate ROS2 things
        env:
          EVENT_NAME: ${{ gitea.event_name }}
        run: |
          # 4. Wait a moment for container to stabilize
          sleep 5

          # 5. Determine if MCU sources changed in latest commit range
          if [ "$EVENT_NAME" = "workflow_dispatch" ]; then
            echo "🟠 Manual dispatch detected; forcing MCU flash"
            CHANGED_MCU="mcu_ws/"
          else
            if git rev-parse HEAD~1 >/dev/null 2>&1; then
              CHANGED_MCU=$(git diff --name-only HEAD~1 HEAD | grep '^mcu_ws/' || true)
            else
              # No previous commit available; default to flashing MCU once
              CHANGED_MCU="mcu_ws/"
            fi
          fi

          if [ -z "$CHANGED_MCU" ]; then
            echo "ℹ️ No changes detected in mcu_ws; skipping MCU flash"
            MCU_FLAG="--skip-mcu"
          else
            echo "🔧 Changes detected in mcu_ws; will flash MCU"
            MCU_FLAG=""
          fi

          # 6. Run unified deployment script inside container (conditional MCU flash, ROS build, then launch test node)
          docker exec -u ubuntu sec26-devcontainer-1 bash -c "python3 /home/ubuntu/scripts/deploy-all.py $MCU_FLAG"

      - name: 🧹 Cleanup
        run: |
          echo "🧹 Cleaning up old images..."
          docker image prune -f

      - name: ⚡ Ensure LED process stops (always)
        if: ${{ always() }}
        run: |
          echo "⚡ Ensuring BOOTLED process is stopped regardless of job outcome"
          # Kill any lingering daemonized gpioset processes
          pkill -f "gpioset.*BOOTLED" || true
          # Explicitly turn the LED on
          gpioset -z -C BOOTLED -c gpiochip0 17=1 || true