name: PlatformIO Build All

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'mcu_ws/**'
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build all PlatformIO environments
        working-directory: mcu_ws/
        shell: bash
        run: |
          # Install dependencies for all environments (PlatformIO will resolve per env)
          pio pkg install || true
          
          # Build all environments defined in platformio.ini
          # `pio run` without -e builds every env
          pio run