name: PlatformIO Build All

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Enter WS
        run: cd mcu_ws/

      - name: Install Pio Packages
        run: pio pkg install 
        working-directory: mcu_ws/       

      - name: Build All Environments
        # Running without '-e' builds all environments found in platformio.ini
        run: pio run
        working-directory: mcu_ws/