name: PlatformIO Build All

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'mcu_ws/**'
      - '.gitea/workflows/platformio-robot.yml'
      - 'ros2_ws/src/mcu_msgs/**'
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Prepare MCU extra packages (mcu_msgs)
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p mcu_ws/extra_packages
          # Copy mcu_msgs from ros2_ws into PlatformIO extra_packages
          if [ -d ros2_ws/src/mcu_msgs ]; then
            rm -rf mcu_ws/extra_packages/mcu_msgs
            cp -a ros2_ws/src/mcu_msgs mcu_ws/extra_packages/mcu_msgs
          else
            echo "mcu_msgs not found at ros2_ws/src/mcu_msgs" >&2
            exit 1
          fi

      - name: Cache PlatformIO packages and build artifacts
        id: pio-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            mcu_ws/.pio
            mcu_ws/.pioenvs
            mcu_ws/libs_external/esp32/micro_ros_platformio/build
            mcu_ws/libs_external/esp32/micro_ros_platformio/libmicroros
            mcu_ws/libs_external/teensy/micro_ros_platformio/build
            mcu_ws/libs_external/teensy/micro_ros_platformio/libmicroros
            ~/.cache/pip
          key: platformio-${{ runner.os }}-${{ hashFiles('mcu_ws/extra_packages/**','mcu_ws/libs_external/**') }}
          restore-keys: |
            platformio-${{ runner.os }}-

      - name: Show PlatformIO cache status
        run: |
          if [ "${{ steps.pio-cache.outputs.cache-hit }}" = 'true' ]; then
            echo "::notice::PlatformIO cache hit"
          else
            echo "::notice::PlatformIO cache miss"
          fi

      - name: Clean microros if cache restored from fallback
        if: steps.pio-cache.outputs.cache-hit != 'true'
        working-directory: mcu_ws/
        run: |
          echo "::notice::Cache restored from fallback key, cleaning microros"
          pio run -e robot -t clean_microros || true

      - name: Install CMake
        # Pin to 3.29.x — CMake 3.28 rejects PlatformIO's arm-cortexm7f-eabi-gcc
        # version "13.20" as unknown; 3.29 fixed that compiler detection issue.
        run: pip install cmake==3.29.6

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build all PlatformIO environments
        working-directory: mcu_ws/
        shell: bash
        run: pio run

      - name: Preview MCU artifacts (count + list)
        shell: bash
        run: |
          set -euxo pipefail
          shopt -s globstar nullglob
          files=(
            mcu_ws/.pio/build/*/firmware.*
            mcu_ws/.pio/build/*/**/*.{bin,hex,elf,uf2}
          )
          echo "Found ${#files[@]} files to upload:";
          for f in "${files[@]}"; do echo " - $f"; done

      - name: Upload MCU build artifacts (all environments)
        uses: actions/upload-artifact@v3
        with:
          name: mcu-build-artifacts-all
          path: |
            mcu_ws/.pio/build/*/firmware.*
            mcu_ws/.pio/build/*/**/*.{bin,hex,elf,uf2}
          if-no-files-found: ignore
          retention-days: 7