name: Deploy Master to Prod

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch all history so we can push to other branches

      - name: Configure Git
        run: |
          git config --global user.name "Gitea Actions"
          git config --global user.email "actions@gitea.local"

      - name: Push to prod
        env:
          PAT: ${{ secrets.EL_HUB_PAT }}
        run: |
          git remote set-url origin https://$PAT@gitea.syndric.org/ieeeucf/SEC26.git
          git push origin HEAD:prod --force