name: Deploy Master to Prod

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch all history so we can push to other branches

      - name: Configure Git
        run: |
          git config --global user.name "Gitea Actions"
          git config --global user.email "actions@gitea.local"

      - name: Push to prod
        env:
          PAT: ${{ secrets.EL_HUB_PAT }}
          USERNAME: ${{ secrets.EL_HUB_USER }}
        run: |
          if [ -z "$USERNAME" ]; then
            echo "ERROR: EL_HUB_USER secret not set (required username for PAT)." >&2
            exit 1
          fi
          # Use HTTPS URL with username:token to authenticate
          git remote set-url origin https://$USERNAME:$PAT@gitea.syndric.org/ieeeucf/SEC26.git
          git push origin HEAD:prod --force