colors:
  yellow:
    color_low: [20, 100, 100]
    color_high: [35, 255, 255]
    hsv_values: [28, 200, 200]
  red:
    color_low: [0, 120, 100]
    color_high: [10, 255, 255]
    hsv_values: [5, 220, 200]
  green:
    color_low: [56, 95, 125]
    color_high: [60, 255, 255]
    hsv_values: [58, 175, 190]
  blue:
    color_low: [100, 120, 100]
    color_high: [130, 255, 255]
    hsv_values: [115, 220, 200]
  purple:
    color_low: [130, 80, 80]
    color_high: [160, 255, 255]
    hsv_values: [145, 180, 200]
