/**
 * @file SensorSubsystem.h
 * @date 12/18/2025
 * @author Generated by Copilot
 * @brief Sensor Subsystem for TOF distance sensors.
 */

#ifndef SENSORSUBSYSTEM_H
#define SENSORSUBSYSTEM_H

#include <BaseSubsystem.h>
#include <TOF.h>
#include <microros_manager_robot.h>
#include <std_msgs/msg/float32_multi_array.h>

#include <vector>

#ifdef USE_TEENSYTHREADS
#include <TeensyThreads.h>
#endif

namespace Subsystem {
class SensorSubsystemSetup : public Classes::BaseSetup {
 public:
  SensorSubsystemSetup(const char* _id,
                       std::vector<Drivers::TOFDriver*> drivers)
      : Classes::BaseSetup(_id), drivers_(drivers) {}
  std::vector<Drivers::TOFDriver*> drivers_;
};

class SensorSubsystem : public IMicroRosParticipant,
                        public Classes::BaseSubsystem {
 public:
  explicit SensorSubsystem(const SensorSubsystemSetup& setup)
      : Classes::BaseSubsystem(setup), setup_(setup) {}

  bool init() override;
  void begin() override {}
  void update() override;
  void pause() override {}
  void reset() override;
  const char* getInfo() override;

  bool onCreate(rcl_node_t* node, rclc_executor_t* executor) override;
  void onDestroy() override;

  void publishData();

#ifdef USE_TEENSYTHREADS
  void beginThreaded(uint32_t stackSize, int /*priority*/ = 1,
                     uint32_t updateRateMs = 100) {
    task_delay_ms_ = updateRateMs;
    threads.addThread(taskFunction, this, stackSize);
  }

 private:
  static void taskFunction(void* pvParams) {
    auto* self = static_cast<SensorSubsystem*>(pvParams);
    self->begin();
    while (true) {
      self->update();
      threads.delay(self->task_delay_ms_);
    }
  }
  uint32_t task_delay_ms_ = 100;
#endif

 private:
  const SensorSubsystemSetup setup_;
  rcl_publisher_t pub_{};
  std_msgs__msg__Float32MultiArray msg_{};
  rcl_node_t* node_ = nullptr;
};
}  // namespace Subsystem

#endif