/**
 * @file SensorSubsystem.h
 * @date 12/18/2025
 * @author Generated by Copilot
 * @brief Sensor Subsystem for TOF distance sensors.
 */

#ifndef SENSORSUBSYSTEM_H
#define SENSORSUBSYSTEM_H

#include <BaseSubsystem.h>
#include <TOF.h>
#include <microros_manager_robot.h>
#include <std_msgs/msg/float32_multi_array.h>

#include <vector>

#include "TimedSubsystem.h"

namespace Subsystem {
class SensorSubsystemSetup : public Classes::BaseSetup {
 public:
  SensorSubsystemSetup(const char* _id,
                       std::vector<Drivers::TOFDriver*> drivers)
      : Classes::BaseSetup(_id), drivers_(drivers) {}
  std::vector<Drivers::TOFDriver*> drivers_;
};

class SensorSubsystem : public IMicroRosParticipant,
                        public Subsystem::TimedSubsystem {
 public:
  explicit SensorSubsystem(const SensorSubsystemSetup& setup)
      : Subsystem::TimedSubsystem(setup), setup_(setup) {}

  bool init() override;
  void begin() override {}
  void update() override;
  void pause() override {}
  void reset() override;
  const char* getInfo() override;

  bool onCreate(rcl_node_t* node, rclc_executor_t* executor) override;
  void onDestroy() override;

  void publishData();

 private:
  const SensorSubsystemSetup setup_;
  rcl_publisher_t pub_{};
  std_msgs__msg__Float32MultiArray msg_{};
  rcl_node_t* node_ = nullptr;
};
}  // namespace Subsystem

#endif
