#!/bin/bash

# This script runs on the HOST machine to ensure the required .env file exists.
# It creates a template .env file if one is not already present, with comments
# describing the necessary configuration for build targets and OS-specific graphics.

# Get the directory where this script is located
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Define the path for the .env file (one level up, same as docker-compose.yml)
ENV_FILE="${SCRIPT_DIR}/../.env"

# --- Check if the .env file already exists ---
if [ -f "${ENV_FILE}" ]; then
    echo "The environment configuration file (${ENV_FILE}) already exists. Skipping creation."
    echo "Please edit it manually if you need to change the settings."
    exit 0
fi

# --- Create the new .env file with configuration comments ---
echo "Creating a template environment configuration file: ${ENV_FILE}"

cat > "${ENV_FILE}" <<EOL
# ----------------------------------------------------------------------
# Project Environment Configuration
# Auto-generated by initialize.sh
# ----------------------------------------------------------------------

# ======================================================================
# 1. BUILD STRATEGY (Multi-Stage Docker)
# ======================================================================
# Controls which stage of the Dockerfile is built.
#
# Options:
#   dev  -> Installs Gazebo, RViz, GDB, and GUI tools. (Best for PC/Laptop)
#   prod -> Minimal runtime only. No simulators. (Best for Robot/Deployment)
#
BUILD_TARGET=prod


# ======================================================================
# 2. GRAPHICS & NETWORK CONFIGURATION
# ======================================================================
# Uncomment the block below that matches your operating system.

# 🐧 LINUX NATIVE CONFIGURATION:
# Use this if you are running Ubuntu/Debian natively.
# DISPLAY_CONFIG=\${DISPLAY}
# NETWORK_MODE_CONFIG=host

# 🍎 WINDOWS / 🍏 MACOS (DOCKER DESKTOP):
# Use this if you are using Docker Desktop.
# Requires an XServer (VcXsrv/XQuartz) installed on host.
#DISPLAY_CONFIG=host.docker.internal:0
#NETWORK_MODE_CONFIG=bridge

# ----------------------------------------------------------------------
# ⚠️  DEFAULT FALLBACK (If you don't uncomment anything above)
# ----------------------------------------------------------------------
# If you leave everything commented, these defaults usually work for 
# Windows/Mac users, but Linux users will lose GUI access.
DISPLAY_CONFIG=host.docker.internal:0
NETWORK_MODE_CONFIG=bridge
EOL

echo "Template file created at: ${ENV_FILE}"
echo "----------------------------------------------------------------"
echo "** ACTION REQUIRED **"
echo "1. Open .env"
echo "2. Check that BUILD_TARGET is set to 'dev' (for simulation)"
echo "3. Uncomment the DISPLAY_CONFIG section matching your OS."
echo "----------------------------------------------------------------"